// Tyr/src/app/app.component.ts
/*
 * Tyr - Allows online game recording in japanese (riichi) mahjong sessions
 * Copyright (C) 2016 Oleg Klimenko aka ctizen <me@ctizen.dev>
 *
 * This file is part of Tyr.
 *
 * Tyr is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Tyr is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Tyr.  If not, see <http://www.gnu.org/licenses/>.
 */

import { ChangeDetectorRef, Component, NgZone } from '@angular/core';
import { RiichiApiService } from './services/riichiApi';
import { MetrikaService } from './services/metrika';
import { I18nService } from './services/i18n';
import { IDB } from './services/idb';
import { ThemeService } from './services/themes/service';
import { Store } from './services/store';
import { HttpClient } from '@angular/common/http';
import {
  HISTORY_INIT,
  INIT_STATE, INIT_WITH_PINCODE,
  STARTUP_WITH_AUTH,
  UPDATE_STATE_SETTINGS
} from './services/store/actions/interfaces';
import { IAppState } from './services/store/interfaces';

@Component({
  selector: 'riichi-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public store: Store;
  public state: IAppState;
  constructor(
    private ref: ChangeDetectorRef,
    private zone: NgZone,
    private api: RiichiApiService,
    private metrika: MetrikaService,
    private http: HttpClient,
    private i18n: I18nService,
    private storage: IDB,
    private themeService: ThemeService
  ) {

    this.store = new Store(this.http, this.i18n);
    this.state = this.store.redux.getState();
    this.metrika.track(MetrikaService.APP_INIT);

    const userTheme = this.storage.get('currentTheme');
    if (userTheme && this.themeService.themeExists(userTheme)) {
      this.themeService.setTheme(userTheme);
    }

    if (this.store.redux.getState().isIos) {
      document.addEventListener(
        'dblclick',
        (e: any) => {
          e.preventDefault();
          e.stopPropagation();
          return false;
        },
        {passive: false}
      );
    }

    this.store.subscribe((newState: IAppState) => {
      this.state = newState;
      this.ref.markForCheck(); // trigger full change detection
    });

    this.i18n.init((localeName: string) => {
      this.metrika.track(MetrikaService.I18N_INIT, { localeName });
      this.store.dispatch({ type: INIT_STATE });
      this.api.setCredentials(this.storage.get('authToken') || '');
      this.store.dispatch({ type: STARTUP_WITH_AUTH, payload: this.storage.get('authToken') || '' });
      this.storage.set('currentLanguage', localeName);
      let loc = window.location.pathname.replace(/^\//, '');
      if (loc.length > 0) {
        this.store.dispatch({ type: INIT_WITH_PINCODE, payload: loc });
      }
      this.store.dispatch({ type: HISTORY_INIT });
      this.store.dispatch({ type: UPDATE_STATE_SETTINGS });
    }, (error: any) => console.error(error));
  }
}

<!--
     Tyr - Allows online game recording in japanese (riichi) mahjong sessions
     Copyright (C) 2016 Oleg Klimenko aka ctizen <me@ctizen.dev>

     This file is part of Tyr.

     Tyr is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.

     Tyr is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Tyr.  If not, see <http://www.gnu.org/licenses/>.
   -->
<div themable class="page-wrap">
  <nav-bar
    [state]="state"
    [dispatch]="store.dispatch"
  ></nav-bar>
  <div class="content">
    <screen-login
      *ngIf="state.currentScreen === 'login'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-login>
    <screen-overview
      *ngIf="state.currentScreen === 'overview'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-overview>
    <screen-new-game
      *ngIf="state.currentScreen === 'newGame'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-new-game>
    <screen-last-results
      *ngIf="state.currentScreen === 'lastResults'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-last-results>
    <screen-outcome-select
      *ngIf="state.currentScreen === 'outcomeSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-outcome-select>
    <screen-players-select
      *ngIf="state.currentScreen === 'playersSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-players-select>
    <screen-yaku-select
      *ngIf="state.currentScreen === 'yakuSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-yaku-select>
    <screen-players-select
      *ngIf="state.currentScreen === 'paoSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-players-select>
    <screen-players-select
      *ngIf="state.currentScreen === 'nagashiSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-players-select>
    <screen-confirmation
      *ngIf="state.currentScreen === 'confirmation'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-confirmation>
    <screen-last-round
      *ngIf="state.currentScreen === 'lastRound'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-last-round>
    <screen-other-tables-list
      *ngIf="state.currentScreen === 'otherTablesList'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-other-tables-list>
    <screen-other-table
      *ngIf="state.currentScreen === 'otherTable'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-other-table>
    <screen-settings
      *ngIf="state.currentScreen === 'settings'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-settings>
    <screen-help
      *ngIf="state.currentScreen === 'help'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-help>
  </div>
</div>

// Tyr/app/index.tsx
/* Tyr - Japanese mahjong assistant application
 * Copyright (C) 2016 Oleg Klimenko aka ctizen
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import * as React from 'react';
import { createRoot } from 'react-dom/client';
import { App } from '#/components/App';
import { Store } from '#/store';
import { I18nService } from '#/services/i18n';
import { IAppState } from '#/store/interfaces';
import { observe } from '#/scripts/dimensionsObserver';
import { registerFrontErrorHandler } from '#/scripts/logFrontError';
import { environment } from '#config';
import { Storage } from '../../Common/storage';

const storage = new Storage(environment.cookieDomain);

// Storage cleanup: use if some trouble happened during logging in
if (window.location.search.startsWith('?clear')) {
  storage.clear();
  window.location.replace(window.location.protocol + '//' + window.location.host);
}

observe();
registerFrontErrorHandler();

const i18nService = new I18nService(storage);
const store = new Store(i18nService, storage);
const root = createRoot(document.getElementById('tyr-root')!);

const doRender = (state: IAppState) => {
  (window as any).__debugInfo = { sh: state.currentSessionHash, p: state.currentPlayerId };
  root.render(
    <App state={state} dispatch={store.dispatch} storage={storage} i18nService={i18nService} />
  );
};

store.subscribe(doRender);
doRender(store.redux.getState());
