// Tyr/src/app/app.component.ts
/*
 * Tyr - Allows online game recording in japanese (riichi) mahjong sessions
 * Copyright (C) 2016 Oleg Klimenko aka ctizen <me@ctizen.dev>
 *
 * This file is part of Tyr.
 *
 * Tyr is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Tyr is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Tyr.  If not, see <http://www.gnu.org/licenses/>.
 */

import { ChangeDetectorRef, Component, NgZone } from '@angular/core';
import { RiichiApiService } from './services/riichiApi';
import { MetrikaService } from './services/metrika';
import { I18nService } from './services/i18n';
import { IDB } from './services/idb';
import { ThemeService } from './services/themes/service';
import { Store } from './services/store';
import { HttpClient } from '@angular/common/http';
import {
  HISTORY_INIT,
  INIT_STATE,
  STARTUP_WITH_AUTH,
  UPDATE_STATE_SETTINGS
} from './services/store/actions/interfaces';
import { IAppState } from './services/store/interfaces';

@Component({
  selector: 'riichi-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public store: Store;
  public state: IAppState;
  constructor(
    private ref: ChangeDetectorRef,
    private zone: NgZone,
    private api: RiichiApiService,
    private metrika: MetrikaService,
    private http: HttpClient,
    private i18n: I18nService,
    private storage: IDB,
    private themeService: ThemeService
  ) {

    this.store = new Store(this.http, this.i18n);
    this.state = this.store.redux.getState();
    this.metrika.track(MetrikaService.APP_INIT);

    const userTheme = this.storage.get('currentTheme');
    if (userTheme && this.themeService.themeExists(userTheme)) {
      this.themeService.setTheme(userTheme);
    }

    if (this.store.redux.getState().isIos) {
      document.addEventListener(
        'dblclick',
        (e: any) => {
          e.preventDefault();
          e.stopPropagation();
          return false;
        },
        {passive: false}
      );
    }

    this.store.subscribe((newState: IAppState) => {
      this.state = newState;
      this.ref.markForCheck(); // trigger full change detection
    });

    this.i18n.init((localeName: string) => {
      this.metrika.track(MetrikaService.I18N_INIT, { localeName });
      this.store.dispatch({ type: INIT_STATE });
      this.api.setCredentials(this.storage.get('authToken') || '');
      this.store.dispatch({ type: STARTUP_WITH_AUTH, payload: this.storage.get('authToken') || '' });
      this.storage.set('currentLanguage', localeName);
      this.store.dispatch({ type: HISTORY_INIT });
      this.store.dispatch({ type: UPDATE_STATE_SETTINGS });
    }, (error: any) => console.error(error));
  }
}

<!--
     Tyr - Allows online game recording in japanese (riichi) mahjong sessions
     Copyright (C) 2016 Oleg Klimenko aka ctizen <me@ctizen.dev>

     This file is part of Tyr.

     Tyr is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.

     Tyr is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Tyr.  If not, see <http://www.gnu.org/licenses/>.
   -->
<div themable class="page-wrap">
  <nav-bar
    [state]="state"
    [dispatch]="store.dispatch"
  ></nav-bar>
  <div class="content">
    <screen-login
      *ngIf="state.currentScreen === 'login'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-login>
    <screen-overview
      *ngIf="state.currentScreen === 'overview'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-overview>
    <screen-new-game
      *ngIf="state.currentScreen === 'newGame'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-new-game>
    <screen-last-results
      *ngIf="state.currentScreen === 'lastResults'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-last-results>
    <screen-outcome-select
      *ngIf="state.currentScreen === 'outcomeSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-outcome-select>
    <screen-players-select
      *ngIf="state.currentScreen === 'playersSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-players-select>
    <screen-yaku-select
      *ngIf="state.currentScreen === 'yakuSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-yaku-select>
    <screen-players-select
      *ngIf="state.currentScreen === 'paoSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-players-select>
    <screen-players-select
      *ngIf="state.currentScreen === 'nagashiSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-players-select>
    <screen-confirmation
      *ngIf="state.currentScreen === 'confirmation'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-confirmation>
    <screen-last-round
      *ngIf="state.currentScreen === 'lastRound'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-last-round>
    <screen-other-tables-list
      *ngIf="state.currentScreen === 'otherTablesList'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-other-tables-list>
    <screen-other-table
      *ngIf="state.currentScreen === 'otherTable'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-other-table>
    <screen-settings
      *ngIf="state.currentScreen === 'settings'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-settings>
    <screen-help
      *ngIf="state.currentScreen === 'help'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-help>
  </div>
</div>

// TyrNext/app/components/App.tsx
/* Tyr - Japanese mahjong assistant application
 * Copyright (C) 2016 Oleg Klimenko aka ctizen
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import { useEffect, useState } from 'react';
import styles from './App.module.css';
import themes from './themes.module.css';
import { IAppState } from '../store/interfaces';
import {
  AppActionTypes,
  GO_TO_CURRENT_GAME,
  HISTORY_INIT,
  INIT_STATE,
  SELECT_EVENT,
  SETTINGS_SAVE_LANG,
  STARTUP_WITH_AUTH,
  TOGGLE_RIICHI_NOTIFICATION,
  UPDATE_CURRENT_GAMES_INIT,
} from '../store/actions/interfaces';
import { Dispatch } from 'redux';
import { IComponentProps } from './IComponentProps';
import { Home } from './screens/Home/Home';
import { Settings } from './screens/Settings/Settings';
import { NewGame } from './screens/NewGame/NewGame';
import { SearchPlayerScreen } from './screens/SearchPlayers/SearchPlayerScreen';
import { SelectHand } from './screens/SelectHand/SelectHand';
import { I18nService } from '../services/i18n';
import { GameResultScreen } from './screens/GameResult/GameResultScreen';
import { Login } from './screens/Login/Login';
import { Log } from './screens/Log/Log';
import { Donate } from './screens/Donate/Donate';
import { EventSelect } from './screens/EventSelect/EventSelect';
import { OtherTablesList } from './screens/OtherTablesList/OtherTablesList';
import { i18n } from './i18n';
import { IStorage } from '../../../Common/storage';
import { v4 } from 'uuid';
import { fontLoader } from '../helpers/fontLoader';
import { ModalDialog } from './base/ModalDialog/ModalDialog';
import clsx from 'classnames';
import { TableCurrentGame } from './screens/TableCurrentGame/TableCurrentGame';
import { TableSelectPlayers } from './screens/TableSelectPlayers/TableSelectPlayers';
import { TableNagashiSelect } from './screens/TableNagashiSelect/TableNagashiSelect';
import { OtherTableView } from './screens/OtherTableView/OtherTableView';
import { TableRoundPreview } from './screens/TableRoundPreview/TableRoundPreview';

interface IProps {
  state: IAppState;
  dispatch: Dispatch<AppActionTypes>;
  storage: IStorage;
  i18nService: I18nService;
}

const CurrentScreen = (props: IComponentProps) => {
  const { state } = props;

  switch (state.currentScreen) {
    case 'login':
      return <Login {...props} />;
    case 'eventSelector':
      return <EventSelect {...props} />;
    case 'overview':
      return <Home {...props} />;
    case 'settings':
      return <Settings {...props} />;
    case 'newGame':
      return <NewGame {...props} />;
    case 'searchPlayer':
      return <SearchPlayerScreen {...props} />;
    case 'currentGame':
      return <TableCurrentGame {...props} />;
    case 'playersSelect':
      return <TableSelectPlayers {...props} />;
    case 'nagashiSelect':
      return <TableNagashiSelect {...props} />;
    case 'confirmation':
      return <TableRoundPreview {...props} />;
    case 'otherTable':
      return <OtherTableView {...props} />;
    case 'handSelect':
      return <SelectHand {...props} />;
    case 'lastResults':
      return <GameResultScreen {...props} />;
    case 'gameLog':
      return <Log {...props} />;
    case 'otherTablesList':
      return <OtherTablesList {...props} />;
    case 'donate':
      return <Donate {...props} />;
  }

  return null;
};

export const App = (props: IProps) => {
  const { state, dispatch, storage, i18nService } = props;
  const currentThemeName = state.settings.currentTheme ?? 'day';
  const [firstStart, setFirstStart] = useState(true);

  useEffect(() => {
    dispatch({ type: INIT_STATE });
    i18nService.init(
      (localeName) => {
        dispatch({ type: SETTINGS_SAVE_LANG, payload: localeName });
        fontLoader(localeName);
      },
      (err) => console.error(err)
    );
    dispatch({ type: HISTORY_INIT });
    const event = storage.getEventId();
    if (event) {
      dispatch({ type: SELECT_EVENT, payload: event });
    }
    const sid = storage.getSessionId() ?? v4();
    storage.setSessionId(sid);
    dispatch({
      type: STARTUP_WITH_AUTH,
      payload: {
        token: storage.getAuthToken() ?? '',
        personId: storage.getPersonId() ?? 0,
        sessionId: sid,
      },
    });

    // goto game screen if there is one
    props.dispatch({ type: UPDATE_CURRENT_GAMES_INIT });
  }, []);

  useEffect(() => {
    if (state.currentSessionHash && firstStart) {
      props.dispatch({ type: GO_TO_CURRENT_GAME });
      setFirstStart(false);
    }
  }, [state.currentSessionHash, firstStart]);

  const curDate = new Date();
  const haveNySpecs =
    (curDate.getMonth() === 11 && curDate.getDate() > 20) ||
    (curDate.getMonth() === 0 && curDate.getDate() < 10);

  const isInStandaloneMode = 'standalone' in window.navigator && window.navigator.standalone;

  const themeStyle = [
    currentThemeName === 'day' ? themes.themeDay : null,
    currentThemeName === 'night' ? themes.themeNight : null,
    currentThemeName === 'junkmat' ? themes.themeJunkmat : null,
  ];

  return (
    <div
      id='screen'
      className={clsx(
        styles.App,
        themes.common,
        ...themeStyle,
        haveNySpecs ? styles.newyear : null
      )}
    >
      <div className={clsx(styles.AppWrap, isInStandaloneMode ? styles.pwafix : null)}>
        <i18n.Provider value={i18nService}>
          <CurrentScreen state={state} dispatch={dispatch} newyear={haveNySpecs} />
          {state.riichiNotificationShown && (
            <ModalDialog
              onClose={() => {
                dispatch({ type: TOGGLE_RIICHI_NOTIFICATION, payload: false });
              }}
              actionPrimary={() => {
                dispatch({ type: TOGGLE_RIICHI_NOTIFICATION, payload: false });
              }}
              actionPrimaryLabel={i18nService._t('OK')}
            >
              {i18nService._t('Please return back and press riichi button for the winner')}
            </ModalDialog>
          )}
        </i18n.Provider>
      </div>
    </div>
  );
};
