// Tyr/src/app/app.component.ts
/*
 * Tyr - Allows online game recording in japanese (riichi) mahjong sessions
 * Copyright (C) 2016 Oleg Klimenko aka ctizen <me@ctizen.dev>
 *
 * This file is part of Tyr.
 *
 * Tyr is free software: you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * Tyr is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with Tyr.  If not, see <http://www.gnu.org/licenses/>.
 */

import { ChangeDetectorRef, Component, NgZone } from '@angular/core';
import { RiichiApiService } from './services/riichiApi';
import { MetrikaService } from './services/metrika';
import { I18nService } from './services/i18n';
import { IDB } from './services/idb';
import { ThemeService } from './services/themes/service';
import { Store } from './services/store';
import { HttpClient } from '@angular/common/http';
import {
  HISTORY_INIT,
  INIT_STATE,
  STARTUP_WITH_AUTH,
  UPDATE_STATE_SETTINGS
} from './services/store/actions/interfaces';
import { IAppState } from './services/store/interfaces';

@Component({
  selector: 'riichi-app',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  public store: Store;
  public state: IAppState;
  constructor(
    private ref: ChangeDetectorRef,
    private zone: NgZone,
    private api: RiichiApiService,
    private metrika: MetrikaService,
    private http: HttpClient,
    private i18n: I18nService,
    private storage: IDB,
    private themeService: ThemeService
  ) {

    this.store = new Store(this.http, this.i18n);
    this.state = this.store.redux.getState();
    this.metrika.track(MetrikaService.APP_INIT);

    const userTheme = this.storage.get('currentTheme');
    if (userTheme && this.themeService.themeExists(userTheme)) {
      this.themeService.setTheme(userTheme);
    }

    if (this.store.redux.getState().isIos) {
      document.addEventListener(
        'dblclick',
        (e: any) => {
          e.preventDefault();
          e.stopPropagation();
          return false;
        },
        {passive: false}
      );
    }

    this.store.subscribe((newState: IAppState) => {
      this.state = newState;
      this.ref.markForCheck(); // trigger full change detection
    });

    this.i18n.init((localeName: string) => {
      this.metrika.track(MetrikaService.I18N_INIT, { localeName });
      this.store.dispatch({ type: INIT_STATE });
      this.api.setCredentials(this.storage.get('authToken') || '');
      this.store.dispatch({ type: STARTUP_WITH_AUTH, payload: this.storage.get('authToken') || '' });
      this.storage.set('currentLanguage', localeName);
      this.store.dispatch({ type: HISTORY_INIT });
      this.store.dispatch({ type: UPDATE_STATE_SETTINGS });
    }, (error: any) => console.error(error));
  }
}

<!--
     Tyr - Allows online game recording in japanese (riichi) mahjong sessions
     Copyright (C) 2016 Oleg Klimenko aka ctizen <me@ctizen.dev>

     This file is part of Tyr.

     Tyr is free software: you can redistribute it and/or modify
     it under the terms of the GNU General Public License as published by
     the Free Software Foundation, either version 3 of the License, or
     (at your option) any later version.

     Tyr is distributed in the hope that it will be useful,
     but WITHOUT ANY WARRANTY; without even the implied warranty of
     MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
     GNU General Public License for more details.

     You should have received a copy of the GNU General Public License
     along with Tyr.  If not, see <http://www.gnu.org/licenses/>.
   -->
<div themable class="page-wrap">
  <nav-bar
    [state]="state"
    [dispatch]="store.dispatch"
  ></nav-bar>
  <div class="content">
    <screen-login
      *ngIf="state.currentScreen === 'login'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-login>
    <screen-overview
      *ngIf="state.currentScreen === 'overview'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-overview>
    <screen-new-game
      *ngIf="state.currentScreen === 'newGame'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-new-game>
    <screen-last-results
      *ngIf="state.currentScreen === 'lastResults'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-last-results>
    <screen-outcome-select
      *ngIf="state.currentScreen === 'outcomeSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-outcome-select>
    <screen-players-select
      *ngIf="state.currentScreen === 'playersSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-players-select>
    <screen-yaku-select
      *ngIf="state.currentScreen === 'yakuSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-yaku-select>
    <screen-players-select
      *ngIf="state.currentScreen === 'paoSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-players-select>
    <screen-players-select
      *ngIf="state.currentScreen === 'nagashiSelect'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-players-select>
    <screen-confirmation
      *ngIf="state.currentScreen === 'confirmation'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-confirmation>
    <screen-last-round
      *ngIf="state.currentScreen === 'lastRound'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-last-round>
    <screen-other-tables-list
      *ngIf="state.currentScreen === 'otherTablesList'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-other-tables-list>
    <screen-other-table
      *ngIf="state.currentScreen === 'otherTable'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-other-table>
    <screen-settings
      *ngIf="state.currentScreen === 'settings'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-settings>
    <screen-help
      *ngIf="state.currentScreen === 'help'"
      [state]="state"
      [dispatch]="store.dispatch"
    ></screen-help>
  </div>
</div>

// Tyr/app/components/App.tsx
/* Tyr - Japanese mahjong assistant application
 * Copyright (C) 2016 Oleg Klimenko aka ctizen
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU General Public License as published by
 *  the Free Software Foundation, either version 3 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU General Public License for more details.
 *
 *  You should have received a copy of the GNU General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import * as React from 'react';
import { useEffect } from 'react';
import '../styles/base.css';
import '../styles/themes.css';
import '../styles/variables.css';
import { IAppState } from '../store/interfaces';
import {
  AppActionTypes,
  HISTORY_INIT,
  INIT_STATE,
  SELECT_EVENT,
  SETTINGS_SAVE_LANG,
  STARTUP_WITH_AUTH,
} from '../store/actions/interfaces';
import { Dispatch } from 'redux';
import { IComponentProps } from './IComponentProps';
import { HomeScreen } from './screens/home/HomeScreen';
import { SettingsScreen } from './screens/settings/SettingsScreen';
import { NewGameScreen } from './screens/new-game/NewGameScreen';
import { SearchPlayerScreen } from './screens/search-players/SearchPlayerScreen';
import { TableScreen } from './screens/table/TableScreen';
import { SelectHandScreen } from './screens/select-hand/SelectHandScreen';
import { I18nService } from '../services/i18n';
import { GameResultScreen } from './screens/game-result/GameResultScreen';
import { LoginScreen } from './screens/login/LoginScreen';
import { LogScreen } from './screens/log/LogScreen';
import { DonateScreen } from './screens/donate/DonateScreen';
import { EventSelectScreen } from './screens/event-select/EventSelectScreen';
import { OtherTablesList } from './screens/other-tables-list/OtherTablesListScreen';
import { i18n } from './i18n';
import { IStorage } from '../../../Common/storage';

interface IProps {
  state: IAppState;
  dispatch: Dispatch<AppActionTypes>;
  storage: IStorage;
  i18nService: I18nService;
}

const CurrentScreen: React.FC<IComponentProps> = (props) => {
  const { state } = props;

  switch (state.currentScreen) {
    case 'login':
      return <LoginScreen {...props} />;
    case 'eventSelector':
      return <EventSelectScreen {...props} />;
    case 'overview':
      return <HomeScreen {...props} />;
    case 'settings':
      return <SettingsScreen {...props} />;
    case 'newGame':
      return <NewGameScreen {...props} />;
    case 'searchPlayer':
      return <SearchPlayerScreen {...props} />;
    case 'currentGame':
    case 'outcomeSelect':
    case 'playersSelect':
    case 'confirmation':
    case 'nagashiSelect':
    case 'paoSelect':
    case 'otherTable':
      return <TableScreen {...props} />;
    case 'handSelect':
      return <SelectHandScreen {...props} />;
    case 'lastResults':
      return <GameResultScreen {...props} />;
    case 'gameLog':
      return <LogScreen {...props} />;
    case 'otherTablesList':
      return <OtherTablesList {...props} />;
    case 'donate':
      return <DonateScreen {...props} />;
  }

  return null;
};

export const App: React.FC<IProps> = (props: IProps) => {
  const { state, dispatch, storage, i18nService } = props;
  const currentThemeName = state.settings.currentTheme ?? 'day';

  useEffect(() => {
    dispatch({ type: INIT_STATE });
    i18nService.init(
      (localeName) => {
        dispatch({ type: SETTINGS_SAVE_LANG, payload: localeName });
      },
      (err) => console.error(err)
    );
    dispatch({ type: HISTORY_INIT });
    const event = storage.getEventId();
    if (event) {
      dispatch({ type: SELECT_EVENT, payload: event });
    }
    dispatch({
      type: STARTUP_WITH_AUTH,
      payload: {
        token: storage.getAuthToken() ?? '',
        personId: storage.getPersonId() ?? 0,
      },
    });
  }, []);

  const curDate = new Date();
  const haveNySpecs =
    (curDate.getMonth() === 11 && curDate.getDate() > 20) ||
    (curDate.getMonth() === 0 && curDate.getDate() < 10);

  const isInStandaloneMode = 'standalone' in window.navigator && window.navigator.standalone;

  return (
    <div id='screen' className={`App theme-${currentThemeName}${haveNySpecs ? ' newyear' : ''}`}>
      <div className={`AppWrap ${isInStandaloneMode ? 'pwafix' : ''}`}>
        <i18n.Provider value={i18nService}>
          <CurrentScreen state={state} dispatch={dispatch} />
        </i18n.Provider>
      </div>
    </div>
  );
};
